image: node:latest

stages:
    - install
    - deploy

install:
    stage: install
    script:
        - npm ci

deploy:
    type: deploy
    stage: deploy
    image: ruby:latest
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - heroku